server:
  port: 10200

spring:
  application:
    name: spring-provider02
  datasource:
#    name: root
    username: root
    password: 123
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=UTF8
    driver-class-name: org.gjt.mm.mysql.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
