server:
  port: 10111

spring:
  application:
    name: springcloud-stream-output

  rabbitmq:
    virtual-host: /patyq
    username: xiaomei
    password: xiaomei
    host: cheeeg.com
    port: 5672
