server:
  port: 10010
spring:
  application:
    name: spring-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
    url: jdbc:mysql:///test?serverTimezone=GMT%2B8

#eureka客户端的yml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10000/eureka
    register-with-eureka: true
    fetch-registry: true
#mybatis:
#  mapper-locations: classpath:src/main/java/resources/mapper/*.xml

mybatis-plus:
  mapper-locations: com/cy/dao/*.xml
#  type-aliases-package: com.cy.dao